### ISSUE TITLE
Compilation on 32bit vs 64bit systems - index type is int32_t vs. int64_t

### ISSUE THREAD

**Issue by dmcconachie** [WPI-ARC/baxter_cartesian_controller#1]
On 32 bit systems this fails to compile do to conversion errors related to the index type. Eigen appears to use int32_t instead of int64_t on 32bit systems. This then causes a compilation error due to -Wconversion and -Werror.

ex: line 636, 648 of eigen_helpers.hpp

![screenshot from 2016-03-29 12_40_39](https://cloud.githubusercontent.com/assets/8689721/14116247/bf38b51e-f5ac-11e5-88d6-536e4aaeca70.png)

**Comment by calderpg** [comment]
Changing that particular line to

```
const Eigen::Vector4cd best_eigenvector = eigen_vectors.col((long)max_eigenvector_index);
```

may fix the problem. I'm not going to put together a 32-bit system just to find out if it works, so you'll have to test on Christian's computer and see if it works.

**Comment by dmcconachie** [comment]
I just had him remove -Wconversion in arc-utilities and that worked. I think the correct fix would be to use Eigen's Index type everywhere that we index into Eigen; but I don't think this is needed moving forward. It would just be the fix to do if we wanted to fix it.

**Comment by dmcconachie** [comment]
Properly speaking this issues is not with the baxter files, this is just where it showed up first when he first tried to build.
